-- RLS 임시 비활성화 (개발/테스트용)
-- 주의: 프로덕션에서는 사용하지 마세요!

ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE scripts DISABLE ROW LEVEL SECURITY;
ALTER TABLE outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE call_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;

-- 테스트 데이터 추가
INSERT INTO companies (name) 
VALUES ('테스트 회사')
ON CONFLICT DO NOTHING;

-- 확인
SELECT * FROM companies LIMIT 1;